version: '3.8'

services:
  # Banco de dados PostgreSQL
  database:
    image: postgres:15-alpine
    container_name: taskmanager-db
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskmanager-network
  
  # Nossa aplicação Spring Boot
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: taskmanager-app
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: jdbc:postgresql://database:5432/taskmanager
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password123
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - taskmanager-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  # Opcional: PGAdmin para administrar o PostgreSQL
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: taskmanager-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@taskmanager.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - database
    networks:
      - taskmanager-network
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local

networks:
  taskmanager-network:
    driver: bridge
